/**
 * Constantes de roles del sistema
 */
export const ROLES = {
  ADMIN: 'Admin',
  EDITOR: 'Editor',
  USUARIO: 'Usuario'
} as const;

/**
 * Constantes de permisos del sistema
 * Estos valores deben coincidir exactamente con los nombres en la base de datos
 */
export const PERMISSIONS = {
  // Configuración - Competidores
  CONFIGURACION_BORRADO_COMPETIDORES: 'CONFIGURACION_BORRADO_COMPETIDORES',
  CONFIGURACION_EDICION_COMPETIDORES: 'CONFIGURACION_EDICION_COMPETIDORES',
  CONFIGURACION_CREACION_COMPETIDORES: 'CONFIGURACION_CREACION_COMPETIDORES',
  
  // Configuración - Motivos
  CONFIGURACION_BORRADO_MOTIVOS: 'CONFIGURACION_BORRADO_MOTIVOS',
  CONFIGURACION_EDICION_MOTIVOS: 'CONFIGURACION_EDICION_MOTIVOS',
  CONFIGURACION_CREACION_MOTIVOS: 'CONFIGURACION_CREACION_MOTIVOS',
  
  // Rechazos - Edición
  RECHAZOS_EDICION_MOTIVOS: 'RECHAZOS_EDICION_MOTIVOS',
  RECHAZOS_EDICION_ESTADO: 'RECHAZOS_EDICION_ESTADO',
  RECHAZOS_EDICION_COMPETIDOR: 'RECHAZOS_EDICION_COMPETIDOR',
  RECHAZOS_EDICION_ACCION_CORRECTORA: 'RECHAZOS_EDICION_ACCION_CORRECTORA',
  RECHAZOS_ENVIADO_ACCION_CORRECTORA: 'RECHAZOS_ENVIADO_ACCION_CORRECTORA',
  
  // Gestión
  ASIGNACION_PERMISOS_USUARIOS: 'ASIGNACION_PERMISOS_USUARIOS',
  ASIGNACION_ROLES_USUARIOS: 'ASIGNACION_ROLES_USUARIOS',
  VISUALIZADO_CONFIGURACION: 'VISUALIZADO_CONFIGURACION',
  VISUALIZADO_USUARIOS: 'VISUALIZADO_USUARIOS'
} as const;

/**
 * Tipo para los roles
 */
export type RoleType = typeof ROLES[keyof typeof ROLES];

/**
 * Tipo para los permisos
 */
export type PermissionType = typeof PERMISSIONS[keyof typeof PERMISSIONS];
